LD_PRELOAD=/soft/compilers/cudatoolkit/cuda-12.2.2/lib64/libcurand.so \
CC=/usr/bin/gcc-12 CXX=/usr/bin/g++-12 \
DS_BUILD_CPU_ADAM=1 \
DS_BUILD_FUSED_ADAM=1 \
DS_BUILD_FUSED_LAMB=1 \
DS_BUILD_SPARSE_ATTN=0 \
DS_BUILD_TRANSFORMER=1 \
DS_BUILD_TRANSFORMER_INFERENCE=1 \
DS_BUILD_STOCHASTIC_TRANSFORMER=1 \
DS_BUILD_UTILS=1 \
DS_BUILD_CUDA_EXT=1 \
DS_BUILD_AIO=1 \
DS_BUILD_ONEBIT_ADAM=1 \
DS_BUILD_ONEBIT_LAMB=1 \
DS_BUILD_HISTORICAL_ITERATOR=1 \
DS_BUILD_QUANTIZER=1 \
DS_BUILD_RANDOM_LTD=1 \
DS_BUILD_MEM_EFF_ATTENTION=1 \
TORCH_CUDA_ARCH_LIST="6.0;6.1;7.0;7.5;8.0;8.6" \
pip install .