compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
fsdp_config: {}
machine_rank: 0 # 1 for second node
main_training_function: main
mixed_precision: fp16
num_machines: 2
num_processes: 8
use_cpu: false